server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations:
          - classpath:/config/
          - classpath:/config/dev/
          - classpath:/config/prod/
    bus:
      enabled: false
  profiles:
    active: native

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka


management:
  endpoints:
    web:
      exposure:
        include: '*'

